### ISSUE TITLE
Trigger SFs

### ISSUE THREAD

**Issue by ossobooker** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#13]
# Muon

## ttbar --> 2b+e+MET (tag) +mu (probe)

- [X] tag trigger: Single Electron
- [ ] Dataset de ttbar (MC)
- [ ] Cortes tight

## WW +X --> e + MET (tag) + mu (probe)

- [X] tag trigger: Single Electron
- [ ] Dataset de WW + X (MC)
- [ ] Cortes tight

# Photon

## Z --> mu+mu (tag) + photon_FSR (probe)

- [X] tag trigger: Double Muon
- [ ] Dataset de DY --> ll (MC)
- [ ] Cortes tight

 - Conversar com  o pessoal do J/Psi? talvez eles já tenham resolvido o problema...

**Comment by ftorrresd** [comment]
https://docs.google.com/presentation/d/1wGLR3HwqMu3JIGiplW5QKJgGV6Dj5XwXuDr4axC8C1w/edit?usp=sharing
