### ISSUE TITLE
Rever os valores das x-sections

### ISSUE THREAD

**Issue by ossobooker** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#14]
https://docs.google.com/spreadsheets/d/1zvvedRr1K4NFylNqxNdkWbFgoMPvh9E9BrqxywBpu-Y/edit#gid=445035962

**Comment by ftorrresd** [comment]
Tomar nota das novas referências, se houverem.

**Comment by ftorrresd** [comment]
Atualizar no código.
