### ISSUE TITLE
Fix branches with mixed Float_t and Double_t types.

### ISSUE THREAD

**Issue by ftorresd** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#17]

**Comment by ftorresd** [comment]
@mrcthiel se eu te der a lista de branches que são float e os que são double, ajuda?

Eu tentei fazer tudo float, mas a conversão tá demorando mais que o próprio código de análise....

**Comment by mrcthiel** [comment]
Eu já tenho e o código já está adaptado. Pode deixar do jeito que está. Só propus colocar tudo float pra diminuir a quantidade de IFs na macro para plotar.

**Comment by ftorresd** [comment]
Blz!
