### ISSUE TITLE
Copy 2016 and 2017 Data

### ISSUE THREAD

**Issue by ossobooker** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#7]

**Comment by ftorrresd** [comment]
@mrcthiel copiou para a área dele (UERJ-USR).

Falta: ZGTo2MuG (2016APV, 2016, 2017 e 2018)
https://github.com/CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD/blob/main/samples/samples_details.py
