### ISSUE TITLE
Plotar variáveis cinemáticas para preselection e signal selection

### ISSUE THREAD

**Issue by ossobooker** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#8]
Ler os outputs files de preselection (`outputs/preselected_*.root`) e signal selection (`outputs/selected_*.root`).

OBS1: os arquivos de signal selection não tem corte de massa (massa do upsilon e do boson).

Plotar e produzir os .png e .pdf, de acordo com o modelo exigido pelo CMS, para:

- [x] boson - pt
- [x] boson - eta
- [x] boson - phi
- [x] boson - mass (blinded)
- [x] upsilon - pt
- [x] upsilon - eta
- [x] upsilon - phi
- [x] upsilon - mass 
- [x] photon - pt
- [x] photon - eta
- [x] photon - phi
- [x] mu_1 (leading) - pt
- [x] mu_1 (leading) - eta
- [x] mu_1 (leading) - phi
- [x] mu_2 (sub-leading) - pt
- [x] mu_2 (sub-leading) - eta
- [x] mu_2 (sub-leading) - phi
- [x] delta eta - upsilon x photon
- [x] delta phi - upsilon x photon
- [x] delta R - upsilon x photon

OBS2: Cada plot deve incluir: Data, Signal e Resonant background.
OBS3: Podemos ter Z e Higgs juntos.

**Comment by ftorresd** [comment]
- [ ] Legenda do Z (Res. Background): Z \rightarrow \mu\mu\gamma_{FSR}
- [ ] Pre-selected --> Normalizado pela área.
- [ ] Selected --> Normalizar pela x-section.

**Comment by ftorresd** [comment]
https://mthiel-public.web.cern.ch/mthiel-public/analysis/
