### ISSUE TITLE
Reweighting das Amostras de Sinal - Z

### ISSUE THREAD

**Issue by ossobooker** [CMSHZUpsilonPhoton/HZUpsilonPhotonRun2NanoAOD#9]
As amostras de sinal foram produzidas com o Z on-shell apenas. 

Um SF deve ser produzido para escalar as amostras de sinal para um amostra de DY.

DY Sample:
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FDYJetsToLL_M-50_TuneCP5*FXFX*%2FRunIISummer20UL1*NanoAOD*v9-106X*%2FNANOAODSIM

- Acessar as LHEPart das duas amostras. 
- Plotar o (TH2) de pT x rapidez (y) para sinal e DY.
- Dividir os dois histogramas para criar os SFs.

**Comment by ftorrresd** [comment]
The signal sample is already NLO. This would make no difference.

One could smear the signal mass distribution using the Rochester corrections?

#46
